In [1]:
import numpy as np 
import gym 
import random

In [2]:
env=gym.make('FrozenLake-v1')

In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [4]:
q_table=np.zeros((state_size,action_size))

In [5]:
total_episodes = 1000000      # Total episodes
learning_rate = 0.5          # Learning rate
max_steps = 19               # Max steps per episode
gamma = 0.95                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.0025            # Exponential decay rate for exploration prob

In [6]:
rewards=[]

for episode in range(total_episodes):
    state=env.reset()
    step=0
    done=False
    total_rewards=0
    for step in range(max_steps):
        exp_exp_tradeoff=random.uniform(0,1)
        if exp_exp_tradeoff>epsilon:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
        new_state,reward,done,info = env.step(action)
        q_table[state,action]= -0.0001+q_table[state,action]+learning_rate*(reward+gamma*np.max(q_table[new_state,:])-q_table[state,action])

        state=new_state
        total_rewards+=reward

        if done==True: 
            break

    epsilon=min_epsilon+(max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(q_table)

Score over time: 0.156007
[[2.02079364e-01 1.05434657e-01 1.00548353e-01 1.06700941e-01]
 [2.78179600e-02 3.77725189e-02 2.23798310e-02 7.84468741e-02]
 [1.83669022e-02 1.43730956e-02 2.35630190e-02 4.68688841e-02]
 [1.63304023e-02 9.90838627e-03 7.81434754e-03 4.15207868e-02]
 [2.62040373e-01 1.14190619e-01 1.08535678e-01 1.06695410e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.49956458e-01 1.30113615e-03 1.12874072e-03 6.79011212e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.42972861e-02 1.75826049e-02 4.24136974e-02 2.62086937e-01]
 [1.00851913e-01 2.13953112e-01 1.96897050e-02 4.59827822e-01]
 [5.92128622e-01 6.85547865e-02 1.25419314e-02 2.71018603e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.57407665e-01 2.86037391e-01 5.04426896e-01 1.77530656e-01]
 [2.86291153e-01 6.83625346e-01 2.23387630e-01 1.98125207e-01]
 [0.00000000e+00 0.00000000e+

In [7]:
env.reset()
wins=0

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    # print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps*100):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(q_table[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            # env.render()
            if new_state == 15:
                wins+=1
                print("We reached our Goal 🏆")
            else:
                print("We fell into a hole ☠️")
            
            # We print the number of step it took.
            print("Number of steps", step)
            
            break
        state = new_state
env.close()
print('TOTAL WINS ', wins)

EPISODE  0
We fell into a hole ☠️
Number of steps 32
EPISODE  1
We fell into a hole ☠️
Number of steps 38
EPISODE  2
We fell into a hole ☠️
Number of steps 5
EPISODE  3
We reached our Goal 🏆
Number of steps 57
EPISODE  4
We fell into a hole ☠️
Number of steps 25
TOTAL WINS  1
